"""
Auto-generated semantic module for sanming
Generated at: 2025-12-05T13:30:19.436429
Version: 1.0.0

对照 Requirements 6.4 - 带 @SemanticRegistry.register 装饰器的 Python 模块
"""

from backend.semantics.core.base import SemanticEntry, SemanticRegistry, NarrativeSnippetExtended
from backend.core.contracts import (
    SnippetRole,
    SourceMetadata,
    ConfigRelation,
    EvidenceChainEntry,
    RelationType,
    EffectDirection,
    ConfidenceLevel,
)


@SemanticRegistry.register(
    semantic_id="smth_v1.0.0_贵格与尊荣双全之象_001",
    book_id="sanming",
    engine_id="bazi"
)
class 贵格与尊荣双全之象(SemanticEntry):
    """
    - 原文（source_text）：

  贵者尊荣之号.命中有官星，得其财气以相资，三奇得其宗，四柱不植鬼病，乃女命尧舜也.经云：无煞女人之命，一贵可作良人.又云：女命无煞逢二德，可两国之封.天德者...
    """
    
    original_text: str = """- 原文（source_text）：

  贵者尊荣之号.命中有官星，得其财气以相资，三奇得其宗，四柱不植鬼病，乃女命尧舜也.经云：无煞女人之命，一贵可作良人.又云：女命无煞逢二德，可两国之封.天德者，非独天月二德，即财为一德，官为一德，加之印食，愈为贵也.如乙亥、丙戌、辛卯、癸巳，辛用乙为财，旺于亥；丙为夫星，坐库归禄巳土.癸水为夫之官，辛金生癸为子，坐巳土与夫禄同位，又是贵神，又为财官双美，乃得夫子俱贵，两遇褒封.

- 分字分词释义：

  - **贵者尊荣之号**：贵，指尊荣、地位与名誉兼具.
  - **三奇得其宗**：三奇多指财、官、印（或食），各得其所、互相资助.
  - **四柱不植鬼病**：命局中无严重鬼煞、病符等破格之神.
  - **无煞女人之命，一贵可作良人**：女命若无七煞横行，逢贵神，则可为贤良之妇，享有尊荣.
  - **二德**：除天月二德外，原文并以财、官、印、食诸吉神扩展为“德”.

- **规范化释义（primary_lang_explained）**：

  “贵格”是在“清格”之上，进一步强调尊荣与位分：

  - 以官星为核心，有财气相资，又有印食为助；
  - 命局少见煞气、病符之类破坏性强的神煞；
  - 再加上德星、贵神等吉曜，则多主夫子俱贵、家庭社会地位皆高.

  原例乙亥、丙戌、辛卯、癸巳：辛金以乙木为财，旺于亥；丙火为夫星，坐库归禄于巳；癸水为夫之官，辛金生癸为子，且子星与夫禄同居巳中，既是贵神，又为财官双美，因此原文以“夫子俱贵，两遇褒封”形容.

- 核心要点：

  - 官星清正、财官印食配合和谐，是“贵格”的骨架.
  - 少煞少凶，德星、贵神相辅，是其上层加分点.
  - 多主伴侣与子女皆有发展空间，家道与个人声望皆较高.

- 详细解说：

  1. **尊荣的来源**  
     - 来自官星代表的身份与责任；  
     - 来自财星代表的资源与给养；  
     - 来自印食代表的学养与气质.三者组合恰当，才称“贵”.

  2. **无煞与有煞的差异**  
     - 无煞并非绝对无挑战，而是煞不横行、不主导局势；  
     - 若煞多而无制，则容易从“贵”转为“险”，在婚姻、健康或声誉上出现反复.

  3. **现代语境下的“贵”**  
     - 可理解为承担较多公共角色、责任与资源的人：如专业人士、管理者、意见领袖等；  
     - 其贵不必然是封号爵位，而是综合能力与道德信用的体现.

 - **完整对等诠释（secondary_lang_full）**：

   The "Noble" pattern takes the clean coordination of Wealth, Officer and Seal one step further and ties it explicitly to status, honour, and public responsibility. In such a chart the Officer star that signifies the spouse is clear, upright, and well supported; Wealth supplies it with resources, while Seal or Food provide learning, temperament, and the ability to carry responsibilities with grace. At the same time, harmful Sha and illness-indicating stars are either absent or kept in check, so that honour is not constantly undermined by hidden dangers.

   In the example, Xin Metal Day Master uses Yi Wood as Wealth, flourishing in Hai; Bing Fire serves as the spouse star sitting in its Lu at Si; and Gui Water acts as the Officer of the spouse, being generated by Xin Metal and sharing the same Si position as the spouse's Lu. This co-location symbolises "spouse and children both honoured" – not necessarily in the sense of formal titles, but as a family line that collectively enjoys recognition and opportunities. Additional "virtue" and "noble" stars further enhance the sense that this chart is invited into higher circles of trust and responsibility.

   For contemporary readers, a Noble configuration points to a life where one's partner and children are more likely to occupy visible, trusted positions in their communities, and where the native herself participates in public or institutional roles. The emphasis is less on personal luxury and more on being entrusted with resources, people, or information – a form of nobility rooted in accountability and contribution rather than in birth alone.

 - 校勘与字词辨析：

  - 原文“女命无煞逢二德，可两国之封”之类说法，本稿在白话中仅作“尊荣之象”理解，不作字面封号断语.
  - “三奇得其宗”在本节按财官印（食）之和谐理解，与其他书中三奇用法可能略有差异，读者宜分辨.
  - **English**：
    - Spirit-star (shensha) terms demystified; fortune cycle descriptions treated as developmental tendencies.

- **叙事素材（narrative_snippets）**：
  - `[ns_smth_07_021]` `[trigger: 贵格定义]` `[factor_trigger: gui_ge_zunrong]` `[role: 主干]` 贵者尊荣之号。 → 《三命通会》卷七#贵格
  - `[ns_smth_07_022]` `[trigger: 官财三奇]` `[factor_trigger: guan_xing_cai_qi AND san_qi_dezong]` `[role: 主干依赖]` 命中有官星，得其财气以相资，三奇得其宗，四柱不植鬼病，乃女命尧舜也。 → 《三命通会》卷七#贵格
  - `[ns_smth_07_023]` `[trigger: 无煞良人]` `[factor_trigger: wu_sha_nv_ming AND yi_gui_liangren]` `[role: 条件分支]` 经云：无煞女人之命，一贵可作良人。 → 《三命通会》卷七#贵格
  - `[ns_smth_07_024]` `[trigger: 夫子俱贵]` `[factor_trigger: fu_zi_ju_gui]` `[role: 总结]` 乃得夫子俱贵，两遇褒封。 → 《三命通会》卷七#贵格"""
    normalized_text_zh: str = """"""
    subject: str = "贵格与尊荣双全之象"
    factor_refs: list = ['new_candidate', 'new_candidate', 'new_candidate', 'new_candidate', 'engine_id', 'bazi_structure_factor_94', 'bazi_semantic', 'bazi_state_water_1', 'bazi_semantic', 'bazi_relation_zi_degree', 'bazi_semantic', 'bazi_factor_8', 'bazi_semantic', 'source_ref', 'rel_smth_07_013', 'guige_caiguanyin', 'rel_smth_07_014', 'fuzi_tonggui', 'rel_smth_07_015', 'zunrong_kechixu', 'evi_smth_07_013', 'guige_caiguanyin', 'rule_guige', 'evi_smth_07_014', 'fuzi_tonggui', 'rule_tonggui', 'evi_smth_07_015', 'xiongsha_fuzai', 'rule_liangren', 'map_smth_07_009', 'map_smth_07_010']
    
    # 叙事素材（包含 trigger_human）
    narrative_snippets: list = [

    ]
    
    # L2.5 因子关系
    related_semantics: list = [

    ]
    
    # L2.5 证据链
    evidence_refs: list = [

    ]
    
    metadata: SourceMetadata = SourceMetadata(
        book_id="sanming",
        chapter="",
        l1_anchor="smth_v1.0.0_贵格与尊荣双全之象_001_L1",
    )
    version: str = "1.0.0"
