"""
Auto-generated semantic module for zipingzhenquan
Generated at: 2025-12-05T13:30:19.492254
Version: 1.0.0

对照 Requirements 6.4 - 带 @SemanticRegistry.register 装饰器的 Python 模块
"""

from backend.semantics.core.base import SemanticEntry, SemanticRegistry, NarrativeSnippetExtended
from backend.core.contracts import (
    SnippetRole,
    SourceMetadata,
    ConfigRelation,
    EvidenceChainEntry,
    RelationType,
    EffectDirection,
    ConfidenceLevel,
)


@SemanticRegistry.register(
    semantic_id="zpzq_v1.0.0_财星之本义与多重象_001",
    book_id="zipingzhenquan",
    engine_id="bazi"
)
class 财星之本义与多重象(SemanticEntry):
    """
    - **原文（source_text）**：
  三十三、论财。
  财为我克，使用之物也，以能生官，所以为美。为财帛，为妻妾，为才能，为驿马，皆财类也。

  财喜根深，不宜太露，然透一位以清用，格...
    """
    
    original_text: str = """- **原文（source_text）**：
  三十三、论财。
  财为我克，使用之物也，以能生官，所以为美。为财帛，为妻妾，为才能，为驿马，皆财类也。

  财喜根深，不宜太露，然透一位以清用，格所最喜，不为之露。即非月令用神，若寅透乙、卯透甲之类，一亦不为过，太多则露矣。然而财旺生官，露亦不忌，盖露不忌，盖露以防劫，生官则劫退，譬如府库钱粮，有官守护，即使露白，谁敢劫之？如葛参政命，壬申、壬子、戊午、乙卯，岂非财露？唯其生官，所以不忌也。

  财格之贵局不一，有财旺生官者，身强而不透伤官，不混七煞，贵格也。

  有财用食生者，身强而不露官，略带一位比劫，益觉有情，如壬寅、壬寅、庚辰、辛巳，杨待郎之命是也。透官身弱，则格坏矣。

  有财格佩印者，盖孤财不贵，佩印帮身，即印取贵。如乙未、甲申、丙申、庚寅，曾参政之命是也，然财印宜相并，如乙未、己卯、庚寅、辛巳，乙与己两不相能，即有好处，小富而已。

  有用食而兼用印者，食与印两不相碍，或有暗官而去食护官，皆贵格也。如吴榜眼命，庚戌、戊子、戊子、丙辰，庚与丙隔两戊而不相克，是食与印不相碍也。如平江伯命，壬辰、乙巳、癸巳、辛酉，虽食印相克，而欲存巳戊官，是去食护官也。反是则减福矣。

  有财用伤官者，财不甚旺而比强，辂露一位伤官以化之，如甲子、辛未、辛酉、壬辰，甲透未库，逢辛为劫，壬以化劫生财，汪学士命是也，财旺无劫而透伤，反为不利，盖伤官本非美物，财轻透劫，不得己而用之。旺而露伤，何苦用彼？徒使财遇伤而死生官之具，安望富贵乎？

  有财带七煞者，或合煞存财，或制煞生财，皆贵格也，如毛状元命，乙酉、庚辰、甲午、戊辰，合煞存财也；李御史命，庚辰、戊子、戊寅、甲寅，制煞生财也。

  有财用煞印者，党煞为忌，印以化之，格成富局，若冬土逢之亦贵格。如赵待郎命，乙丑、丁亥、己亥、丙子，化煞而即以解冻，又不露财以杂其印，所以贵也。若财用煞印而印独，财煞并透，非特不贵，亦不富也。

  至于壬生午月，癸生巳月，单透财而亦贵，又月令有暗官也。如丙寅、癸巳、癸未、壬戌，林尚书命是也。又壬生巳月，单透财而亦贵，以其透丙藏戊，弃煞就财，美者存在赠者弃也。如丙辰、癸巳、壬戌、壬寅，王太仆命是也。

  至于劫刃太重，弃财就煞，如一尚书命，丙辰、丙申、丙午、壬辰，此变之又变者也。

- 原注（原文注解）：
  　　本章总论“财格”的多种成局方式及其贵贱高下，核心在于：
  - 财本为“我所克”的对象，却因能“生官”而成为吉用；
  - 财不仅代表钱财，还象征配偶、才能、流动（驿马）等诸多现实面向；
  - 财喜“根深而有节制”，过多暴露反成破绽，但若“财旺生官”，则“露而不忌”。

  首段强调财之本义与象：
  - “财为我克，使用之物”：财是我可以支配、运用的外在资源；
  - “以能生官，所以为美”：从结构角度，财→官→我，是一条合理的社会路径；
  - 财同时对应：财富（财帛）、配偶（妻妾）、能力（才能）、行动与迁移（驿马）。

  继而提出“财喜根深、不宜太露”的原则：
  - 地支有根、天干透一位财为最美：既有实质，又不过度显露；
  - 即便财非月令用神，只要透一位清财，仍能成局；
  - 多透则“露”，易被比劫耗夺；
  - 但若“财旺生官”，露出反而吉：
    - 因为透财可防比劫暗夺；
    - 官为护财之神，譬如“府库有官守护”，纵然“露白”，亦难被劫。

  后文分条论诸种财格：
  1) **财旺生官格**：
     - 要点：身强、财旺、有官而不透伤官、不混七煞；
     - 这是最典型、最稳定的富贵之财格。
  2) **财用食生格**：
     - 食神生财，财再生官；
     - 身强而不露官，微带比劫则“有情”；
     - 一旦透官而身弱，则“格坏”。
  3) **财格佩印**：
     - “孤财不贵”，须有印以帮身、扶官；
     - 财印并见且相得，则可“印取贵”；
     - 若财印不和，彼此相斥，则仅“小富”。
  4) **财格用食兼印**：
     - 食、印互不相碍，或暗官在后、去食护官；
     - 既有生财之食，又有护身之印，格局清而有情。
  5) **财用伤官格**：
     - 原理是以伤官化比劫生财；
     - 仅在财不甚旺而比肩强时不得已而用；
     - 若财旺无劫而再透伤，则反为不利，是“以病为药”。
  6) **财带七煞格**：
     - 或合煞存财，或制煞生财；
     - 利用煞的力量来护财、成权，属“险中求贵”。
  7) **财用煞印格**：
     - 以煞为病，以印为药；
     - 印化煞而不露财，使财印相得，成富甚至贵格；
     - 若财煞并透而印微弱，则“非特不贵，亦不富”。
  8) **单透财而贵者**：
     - 如壬午、癸巳月，财透而月令暗藏官；
     - 或壬生巳月，透丙藏戊，“弃煞就财”；
     - 属于“隐中有官”的精细财格。
  9) **弃财就煞格**：
     - 劫刃太重，弃财从煞，是“变之又变”的格局；
     - 已近从格与变格之域，应在外格另详。

- 分字分词释义：
  - 财：我所克之物，代表资源、物质、配偶、才能、行动力等。
  - 根深：有地支之根、藏干充足，非虚浮之财。
  - 太露：财星在天干过多、或无根而泛，易招比劫克耗。
  - 财旺生官：财有根、有力，能持续生官而不被劫坏。
  - 食生财：食神泄身生财，财再生官，构成一条柔顺之链。
  - 孤财：有财而无印、无比，身难承财，或财易被夺。
  - 佩印：佩戴印绶，以印护身、护官、护财。
  - 财用伤官：以伤官转化比劫，对财格是偏锋之用法。
  - 合煞存财 / 制煞生财：通过合化或制伏七煞，使财不被煞破，反得其力。
  - 煞印相生：七煞生印，印护身与财，是高阶格局之一。

- **规范化释义（primary_lang_explained）**：
  从工程角度看，“财格”其实是在回答：
  > 一个命局如何驾驭资源，使之生官成名，而不是反被资源拖累？

  核心逻辑可以拆为三层：
  1) **财的量与位置**：
     - 有根 → 才是真财；
     - 透一位 → 足以清用；
     - 透多位 → 容易“露白”，被比劫抢夺，或令日主过度追逐财利。
  2) **财与官、身、印之间的关系**：
     - 最佳路径是“身→食（伤）→财→官→身”的闭环；
     - 身弱财旺 → 必须有印、比来承财，或化财生官、印，变负担为动力；
     - 身强财轻 → 可以多走财运、食伤运，发展财富与才能。
  3) **财与煞、伤官的险象**：
     - 财党煞则伤身，财生官则护身；
     - 财配伤官，若用得其所，则“化劫生财”；
     - 财配七煞，如能合煞存财、制煞生财，则是“险中取贵”。

- **完整对等诠释（secondary_lang_full）**：  
  Wealth, as the star that the Day Master controls, gathers many meanings: money and assets, the spouse in many charts, as well as the concrete projects and opportunities through which one exerts effort. Good Wealth is not simply a large quantity sitting in the open; it prefers to have deep roots, be reasonably protected, and be integrated into a broader structure of Officer, Printing and body strength. Exposed but unguarded Wealth, without Officer or Printing to watch over it, is easily robbed by Peers, consumed by burdens, or turned into a source of constant anxiety.

  Noble Wealth patterns are those in which Wealth clearly serves a role within the system: feeding a clean Officer for positions of responsibility, being generated by Food in a way that matches the Day Master’s capacity, or pairing with Printing and Hurting Officer to turn what would otherwise be loss or competition into productive circulation. Lone, scattered Wealth without roots or protection rarely brings lasting benefit. What matters is always how Wealth is situated: whom it serves—Officer, Killing or the self—and whether luck reinforces that healthy function or twists Wealth into an uncontrollable burden.

- 详细解说：
  - 文中多处借官场比喻财：
    - “府库钱粮，有官守护” → 财需要制度与权力来保护；
    - 没有官印护持的显露之财，极易招来比劫、盗贼、破败。
  - 在现代语境下：
    - 财格佳者，多见于能驾驭资源、管理资产、善用才干之人；
    - 财格偏枯或失衡者，往往在财富与关系上多波折，或为财所累。

- **核心要点**：
  - 财为我克，使用之物也，以能生官，所以为美
  - 财喜根深，不宜太露，透一位以清用，格所最喜
  - 财旺生官，露亦不忌，如府库钱粮有官守护
  - 财旺生官格：身强不透伤官不混七煞
  - 财用食生格：身强不露官，略带比劫益觉有情
  - 财格佩印：孤财不贵，佩印帮身即印取贵
  - 财用伤官：财不甚旺而比强，不得已而用之
  - 财带七煞：合煞存财或制煞生财
  - 财用煞印：党煞为忌，印以化之，格成富局

- **叙事素材（narrative_snippets）**：
  - `[ns_zpzy_515]` `[trigger: 财格]` `[role: 主干]` `[factor_trigger: cai_wei_wo_ke AND shiyong_zhiwu AND neng_sheng_guan_weimei]` 财为我克，使用之物也，以能生官，所以为美。 → 《子平真诠》#下卷
  - `[ns_zpzy_516]` `[trigger: 财格]` `[role: 主干]` `[factor_trigger: cai_wei_caibo_qiqie_caineng_yima]` 为财帛，为妻妾，为才能，为驿马，皆财类也。 → 《子平真诠》#下卷
  - `[ns_zpzy_517]` `[trigger: 财格]` `[role: 主干]` `[factor_trigger: cai_xi_genshen_buyi_tailu AND tou_yiwei_qingyong]` 财喜根深，不宜太露，然透一位以清用，格所最喜。 → 《子平真诠》#下卷
  - `[ns_zpzy_518]` `[trigger: 财旺生官]` `[role: 条件分支]` `[factor_trigger: caiwang_shengguan AND lu_yi_buji AND you_guan_shouhu]` 财旺生官，露亦不忌，譬如府库钱粮，有官守护，即使露白，谁敢劫之？ → 《子平真诠》#下卷
  - `[ns_zpzy_519]` `[trigger: 财旺生官格]` `[role: 条件分支]` `[factor_trigger: caiwang_shengguan AND shenqiang_bu_tou_shangguan AND bu_hun_qisha]` 有财旺生官者，身强而不透伤官，不混七煞，贵格也。 → 《子平真诠》#下卷
  - `[ns_zpzy_520]` `[trigger: 财用食生]` `[role: 条件分支]` `[factor_trigger: cai_yong_shi_sheng AND shenqiang_bu_luguan AND lve_dai_bijie]` 有财用食生者，身强而不露官，略带一位比劫，益觉有情。 → 《子平真诠》#下卷
  - `[ns_zpzy_521]` `[trigger: 财格佩印]` `[role: 条件分支]` `[factor_trigger: gucai_bugui AND peiyin_bangshen AND ji_yin_qugui]` 孤财不贵，佩印帮身，即印取贵。 → 《子平真诠》#下卷
  - `[ns_zpzy_522]` `[trigger: 财用伤官]` `[role: 条件分支]` `[factor_trigger: cai_bushenwang_er_biqiang AND lu_shangguan_yihua]` 财不甚旺而比强，辂露一位伤官以化之。 → 《子平真诠》#下卷
  - `[ns_zpzy_523]` `[trigger: 财带七煞]` `[role: 条件分支]` `[factor_trigger: cai_dai_qisha AND (hesha_cuncai OR zhisha_shengcai)]` 有财带七煞者，或合煞存财，或制煞生财，皆贵格也。 → 《子平真诠》#下卷
  - `[ns_zpzy_524]` `[trigger: 财用煞印]` `[role: 条件分支]` `[factor_trigger: dangsha_weiji AND yin_yi_huazhi AND gecheng_fuju]` 党煞为忌，印以化之，格成富局。 → 《子平真诠》#下卷

#### 语义因子提取（因子层）

| 因子类型 | 因子标签（人话） | 因子ID（必填） | 因子来源 | 角色/位置 | 取值/约束 | engine_id | 备注 |
|----------|------------------|--------------------|----------|----------|----------|-----------|------|
| 结构类   | 财根深浅         | cai_genshen_qianshen        | new_candidate | 资源基础     | 无根 / 一根 / 多根                                     | bazi_rule_engine | 影响财富的稳定性与持续性   |"""
    normalized_text_zh: str = """"""
    subject: str = "财星之本义与多重象"
    factor_refs: list = ['cai_xing', 'cai_genshen', 'cai_tailu', 'cai_wang_shengguan', 'gu_cai', 'caige_peiyin', 'cai_yong_shisheng', 'cai_dai_qisha', 'engine_id', 'cai_xing', 'bazi_rule_engine', 'cai_genshen', 'bazi_rule_engine', 'cai_toulu', 'bazi_rule_engine', 'cai_guan_guanxi', 'bazi_rule_engine', 'cai_jie_guanxi', 'bazi_rule_engine', 'caiwang_shengguan_ge', 'bazi_rule_engine', 'caiyong_shisheng_ge', 'bazi_rule_engine', 'caige_peiyin_ge', 'bazi_rule_engine', 'caiyong_shangguan_ge', 'bazi_rule_engine', 'caidai_qisha_ge', 'bazi_rule_engine', 'caiyong_shayin_ge', 'bazi_rule_engine', 'source_ref', 'rel_zpzq_33_01', 'cai_xing', 'rel_zpzq_33_02', 'guan_xing', 'rel_zpzq_33_03', 'cai_genshen', 'rel_zpzq_33_04', 'shishen', 'rel_zpzq_33_05', 'yinxing', 'rel_zpzq_33_06', 'shangguan', 'rel_zpzq_33_07', 'hege_hesha', 'rel_zpzq_33_08', 'shishen', 'rel_zpzq_33_09', 'yinxing', 'evi_zpzq_33_01', 'rule_cai_shengguan_mei', 'evi_zpzq_33_02', 'rule_cai_genshen_touyiwei', 'evi_zpzq_33_03', 'rule_caiwang_shengguan_lubujie', 'evi_zpzq_33_04', 'caiwang_shengguan_ge', 'rule_caiwang_shengguan_ge', 'evi_zpzq_33_05', 'rule_gucai_peiyin_gui', 'evi_zpzq_33_06', 'rule_shangguan_huajie_shengcai', 'evi_zpzq_33_07', 'caidai_qisha_ge', 'rule_caidai_qisha_gui', 'evi_zpzq_33_08', 'caiyong_shayin_ge', 'rule_shayin_xiangsheng_fucai', 'concept_resource_control', 'concept_protection_mechanism', 'concept_balance_support', 'concept_conversion_strategy']
    
    # 叙事素材（包含 trigger_human）
    narrative_snippets: list = [

    ]
    
    # L2.5 因子关系
    related_semantics: list = [

    ]
    
    # L2.5 证据链
    evidence_refs: list = [

    ]
    
    metadata: SourceMetadata = SourceMetadata(
        book_id="zipingzhenquan",
        chapter="",
        l1_anchor="zpzq_v1.0.0_财星之本义与多重象_001_L1",
    )
    version: str = "1.0.0"
