"""
Auto-generated semantic module for astrology_personality
Generated at: 2025-12-05T13:31:46.238060
Version: 1.0.0

对照 Requirements 6.4 - 带 @SemanticRegistry.register 装饰器的 Python 模块
"""

from backend.semantics.core.base import SemanticEntry, SemanticRegistry, NarrativeSnippetExtended
from backend.core.contracts import (
    SnippetRole,
    SourceMetadata,
    ConfigRelation,
    EvidenceChainEntry,
    RelationType,
    EffectDirection,
    ConfidenceLevel,
)


@SemanticRegistry.register(
    semantic_id="ap_v1.0.0_entry_5__harmonic_astrology_in_001",
    book_id="astrology_personality",
    engine_id="astro"
)
class Entry5HarmonicAstrologyIn(SemanticEntry):
    """
    **Source Text** (Lines 6958-7093):
> Basic Elements in "Harmonic Astrology"... We have often called ...
    """
    
    original_text: str = """**Source Text** (Lines 6958-7093):
> Basic Elements in "Harmonic Astrology"... We have often called such a type of astrology Harmonic Astrology, because it provides a basis for the harmonization and integration of the human psyche. It considers the birth-chart as the life-chord of the individual being and destiny it symbolizes...
>
> To help man fulfill the wholeness of his being and perform the total score of his Destiny—such is the purpose of Harmonic Astrology. The birth-chart is the key to the wholeness of an individual and of his outer manifestation—his Destiny...
>
> Thus we have isolated three elements... Houses refer to the structure of individual selfhood. Signs of the zodiac refer to the collective factor, the substance of being. Planets refer to the energies generated by the constantly changing relation of collective to individual factors.

**Key Term Analysis**:
- **Harmonic Astrology**: `harmonization and integration of psyche` / `birth-chart as life-chord`
- **Purpose**: `fulfill wholeness of being` / `perform total Destiny score`
- **Three elements**: `Houses (individual structure) + Signs (collective substance) + Planets (relational energies)`
- **Personality**: `sum total of patterns of behavior` / `blend of individual and collective`

**English Paraphrase (Primary Language)**:
**Harmonic Astrology** aims at "harmonization and integration of the human psyche," viewing the birth-chart as "the life-chord of the individual." Its purpose: "help man fulfill the wholeness of his being and perform the total score of his Destiny."

Three fundamental elements: **Houses** = individual selfhood structure; **Signs** = collective substance; **Planets** = energies from individual-collective relationship. "The sum total of the planets... represents the personality as a whole."

**Complete Chinese Interpretation (Secondary Language)**:
**和谐占星学**旨在"人类心理的和谐化与整合"，将出生图视为"个体的生命和弦"。其目的："帮助人类实现其存在的完整性并演奏其命运的完整乐谱。"

三个基本要素：**宫位** = 个体自性结构；**星座** = 集体物质；**行星** = 来自个体-集体关系的能量。"所有行星的总和……代表整体人格。"

**Narrative Snippets**:
- `[ns_aop_153]` `[trigger: harmonic_astrology]` `[factor_trigger: astro_harmonic AND astro_harmonic_frame]` `[role: 主干]` Harmonic Astrology: harmonization of psyche, birth-chart as life-chord, fulfill wholeness. → L6968-6987
- `[ns_aop_154]` `[trigger: three_elements]` `[factor_trigger: astro_elements]` `[role: 总结]` Three elements: Houses (individual) + Signs (collective) + Planets (relational energies). → L7030-7056"""
    normalized_text_zh: str = """"""
    subject: str = "Entry 5: Harmonic Astrology—Integration and Purpose"
    factor_refs: list = ['astro_harmonic', 'astro_three_elements']
    
    # 叙事素材（包含 trigger_human）
    narrative_snippets: list = [

    ]
    
    # L2.5 因子关系
    related_semantics: list = [

    ]
    
    # L2.5 证据链
    evidence_refs: list = [

    ]
    
    metadata: SourceMetadata = SourceMetadata(
        book_id="astrology_personality",
        chapter="",
        l1_anchor="ap_v1.0.0_entry_5__harmonic_astrology_in_001_L1",
    )
    version: str = "1.0.0"
