"""
Auto-generated semantic module for planets_in_transit
Generated at: 2025-12-05T13:30:20.206918
Version: 1.0.0

对照 Requirements 6.4 - 带 @SemanticRegistry.register 装饰器的 Python 模块
"""

from backend.semantics.core.base import SemanticEntry, SemanticRegistry, NarrativeSnippetExtended
from backend.core.contracts import (
    SnippetRole,
    SourceMetadata,
    ConfigRelation,
    EvidenceChainEntry,
    RelationType,
    EffectDirection,
    ConfidenceLevel,
)


@SemanticRegistry.register(
    semantic_id="pit_v1.0.0_uranus_in_the_twelfth_house__天_001",
    book_id="planets_in_transit",
    engine_id="astro"
)
class UranusInTheTwelfthHouse天(SemanticEntry):
    """
    **Source Text** (Lines 14797-14808+):
> Effects quite subtle but important. Manifestations: sudden e...
    """
    
    original_text: str = """**Source Text** (Lines 14797-14808+):
> Effects quite subtle but important. Manifestations: sudden events clearly result of past actions; unconscious compulsions and compulsive behavior; upsets involving institutions; sudden disclosure of secrets and hidden things; sudden acts by persons not seeming to work against you. All are upsets, surprises, instability generated by factors you are unaware of. Typically own unconscious mind most involved. Even "secret enemies" are indirectly involved with your unconscious—you attract them through unconscious patterns.

**English Paraphrase**: Subtle but important effects. Sudden events from past actions. Unconscious compulsions. Secrets disclosed. Hidden factors cause upsets. Own unconscious most involved. Even secret enemies attracted through unconscious patterns.

**Complete Chinese Interpretation**: 微妙但重要的影响。过去行为导致的突发事件。无意识的冲动。秘密被揭露。隐藏因素导致动荡。自己的无意识最相关。甚至秘密敌人也是通过无意识模式吸引的。

**Narrative Snippets**:
- `[ns_pit_ur012]` `[trigger: uranus_transit_house_12]` `[factor_trigger: astro_transit_uranus AND astro_house_12]` `[role: 主干]` Subtle but important. Unconscious patterns surface. Secrets disclosed. Hidden factors cause upsets. → PIT Ch11 Uranus-12H"""
    normalized_text_zh: str = """"""
    subject: str = "Uranus in the Twelfth House (天王星过境第十二宫)"
    factor_refs: list = []
    
    # 叙事素材（包含 trigger_human）
    narrative_snippets: list = [

    ]
    
    # L2.5 因子关系
    related_semantics: list = [

    ]
    
    # L2.5 证据链
    evidence_refs: list = [

    ]
    
    metadata: SourceMetadata = SourceMetadata(
        book_id="planets_in_transit",
        chapter="",
        l1_anchor="pit_v1.0.0_uranus_in_the_twelfth_house__天_001_L1",
    )
    version: str = "1.0.0"
